### ISSUE TITLE
Menu is sometimes off in IntelliJ IDEA (java)

### ISSUE THREAD

**Issue by derkoe** [microsoft/wslg#341]
Environment

```none
Windows build number: 10.0.22000.0
Your Distribution version: 20.04
Your WSLg version: 1.0.24
```

# Steps to reproduce

Install IntellIJ in Ubuntu (`umake ide idea-ultimate`) and then launch the IDE (for example with `idea &`). Open any menu.

**WSL logs**: 

* [weston.log](https://github.com/microsoft/wslg/files/6742362/weston.log)
* [pulseaudio.log](https://github.com/microsoft/wslg/files/6742357/pulseaudio.log)
* versions.txt
    ```
    WSLg ( x86_64 ): 1.0.24+Branch.main.Sha.b42023b5fed7567955f4c6c36123a5cf22e9292a
    Mariner: VERSION="1.0.20210224"
    FreeRDP: b05321cd4e6a862aef76163a69db4e1910245736
    weston: ed4f3bbbf5efbd5bde880704bc03497f2446c3f2
    pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
    mesa:
    ```

#  Expected behavior

The menu should be displayed in the correct position.

# Actual behavior

The menu is lower and to the right so that you cannot navigate with a mouse.  As a workaround you can use Alt-Menukey.

![image](https://user-images.githubusercontent.com/123199/123993620-e1d01b80-d9cc-11eb-9f87-85c2e818be08.png)
